### PR TITLE
Move to new hyperledger-solang org

### PR DESCRIPTION
**Pull request by seanyoung**
solang has moved from https://github.com/hyperledger/ to https://github.com/hyperledger-solang/

### CODE REVIEW

**Comment by ryjones** [comment]
You can probably remove `.github/workflows/dco.yml` - the new DCO bot is run by CNCF and is more stable.

**Comment by seanyoung** [comment]
@ryjones DCO is preventing merge after I removed `.github/workflows/dco.yml`

**Comment by seanyoung** [comment]
See below:
image

**Comment by ryjones** [comment]
[found it](https://github.com/hyperledger-solang/solang/settings/branches)

**Review by ryjones — APPROVED** [review]
lgtm

**Pull request merged**
